### ISSUE TITLE
Support for SSH based git connection to use deploy keys for extra security

### ISSUE THREAD

**Issue by jikuja** [sinedied/publish-devto#3]
Personal Access Tokens(PAT) gives access to all repositories. 

SSH based deploy keys should be used instead of PAT and it requires using SSH keys(repository based deploy keys). Ref: https://docs.github.com/en/developers/overview/managing-deploy-keys#machine-users

Not sure how feasible this this feature is to do.

**Comment by sinedied** [comment]
I'm not sure too how that would work on github actions CI, if you have some ideas on this don't hesitate to propose a PR

**Comment by sinedied** [comment]
I'm closing this one as you don't need a PAT with the new v2 unless you use protected branches, the default one used for GHA is enough.
