### ISSUE TITLE
Consider making commit email configurable

### ISSUE THREAD

**Issue by jikuja** [sinedied/publish-devto#4]
Git commits created by action are using hardcoded name, email and commit messages: https://github.com/sinedied/publish-devto/blob/master/lib/git.js#L4-L6 I think that at least email should be configurable by action user.

**Comment by sinedied** [comment]
That should not be too complicated, I'll take a look 👍

**Comment by sinedied** [comment]
You can now configure commiter name and email in the latest version by adding:
```
        env:
          GIT_COMMITTER_NAME: myname
          GIT_COMMITTER_EMAIL: my@email.com
```
